Users_FD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"

# user/
urlpatterns = [
    # user
    url(r'^$', views.file_management, name="index"),  # 主页跳转 - TBD

    url(r'^register/$', views.register, name='register'),

    url(r'^login/$', views.login, name='login'),

    url(r'^logout/$', views.logout, name='logout'),

    url(r'^password_reset_by_user$', views.password_reset_by_user, name='password_reset_by_user'),

    url(r'^password_reset_by_email', views.password_reset_by_email, name='password_reset_by_email'),

    url(r'^user_homepage/$', views.homepage, name='homepage'),


    # group
    url(r'^group_management/$', views.group_management, name='group_management'),

    url(r'^shared_group_management/$', views.shared_group_management, name='shared_group_management'),

    url(r'^create_group/$', views.create_group, name='create_group'),

    url(r'^(?P<group_id>[0-9a-f-]+)$', views.edit_group, name='edit_group'),

    url(r'^delete_member/$', views.delete_member, name='delete_member'),
    # url(r'^(?P<group_id>[0-9a-f-]+)/delete_member/$', views.delete_member, name='delete_member'),

    url(r'^add_member/$', views.add_member, name='add_member'),

    url(r'^delete_group/$', views.delete_group, name='delete_group'),



    # file
    url(r'^file_upload/$', views.file_upload, name='file_upload'),

    url(r'^file_management/$', views.file_management, name='file_management'),
    url(r'^file_management_by_modify_time/$', views.file_management_by_modify_time, name='file_management_by_modify_time'),
    url(r'^file_management_by_filename/$', views.file_management_by_filename, name='file_management_by_filename'),

    url(r'^shared_file_view/$', views.shared_file_view, name='shared_file_view'),

    url(r'^group_files_view/$', views.group_file_view, name='group_files_view'),

    url(r'^delete_file/$', views.delete_file, name='delete_file'),

    url(r'^share_file/$', views.share_file, name='share_file'),

    url(r'^share_file_to_group/$', views.share_file_to_group, name='share_file_to_group'),

    url(r'^edit_file/$', views.edit_file, name='edit_file'),

    url(r'^share_status/(?P<file_guid>[0-9a-f-]+)$', views.share_status_management, name='share_status_management'),

    url(r'^remove_share_record/$', views.remove_share_record, name='remove_share_record'),

    # url(r'^sort_file/$', views.sort_file, name='sort_file'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import uuid


# 用户信息
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    cellphone = models.CharField(max_length=20, blank=True, default='')
    user_uuid = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False, primary_key=True)

    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)


post_save.connect(create_user_profile, sender=User)


# 文件信息
class File(models.Model):
    gu_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False, primary_key=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='file_owner')

    # 正式server只存文件路径 #
    # path = models.CharField(max_length=256)
    path = models.FileField(upload_to='user_files/')

    # @property
    # def filename(self):
    #     name = self.path.name.split("/")[1].replace('_', ' ').replace('-', ' ')
    #     return name
    filename = models.CharField(max_length=255)

    total_page = models.PositiveIntegerField(default=0)
    date_uploaded = models.DateTimeField('date file uploaded', auto_now_add=True)
    last_modified = models.DateTimeField('date last modified', auto_now=True)

    def __str__(self):
        return self.filename + " ; " + self.owner.username + " ; " + self.path.url


# 分享组信息 (组长 + 组_ID)
class Group(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='group_owner')
    group_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False)
    group_name = models.CharField(max_length=255, default='', unique=True)

    def __str__(self):
        return self.owner.username + ' ；' + str(self.group_name)


# 标注信息
class Label(models.Model):
    label_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False, primary_key=True)
    labeled_file = models.ForeignKey(File, on_delete=models.CASCADE, default=None)
    editor = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    category = models.CharField(max_length=255, default='')  # figure / table / ...
    coordinate = models.CharField(max_length=255, default='')
    status = models.CharField(max_length=255, default='')  # 识别 / 删除 / 添加


# 文件分享记录
class FileShare(models.Model):
    file_share_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True,
                                     editable=False, primary_key=True)
    shared_file = models.ForeignKey(File, on_delete=models.CASCADE, default=None)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="shared_file_owner", default=None)
    sharer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="shared_file_sharer", default=None)
    # type = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="type", default=None)


# 群成员信息
class GroupMember(models.Model):
    share_group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None)
    shared_user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return str(self.share_group.group_name) + ' ; ' + self.shared_user.username


# 分享的群文件信息
class GroupFiles(models.Model):
    share_group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None,
                                    related_name="file_share_group")
    shared_file = models.ForeignKey(File, on_delete=models.CASCADE, default=None,
                                    related_name='shared_file')

    def __str__(self):
        return str(self.share_group.group_name) + " ; " + str(self.shared_file.filename)
    
    

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import File


class UserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(required=True)
    cellphone = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ['username', 'cellphone', 'email', 'password', ]


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['path', ]

user/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse
from .models import *

# User Authentications
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import UserProfileForm, FileUploadForm

# File Upload
from django.http import JsonResponse
from django.db.models import Q
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt


UPLOAD_FILE_TYPES = ['pdf', ]

# Create your views here.

#
# 用户系统
#
def register(request):
    form = UserProfileForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.profile.cellphone = form.cleaned_data['cellphone']
        # user.profile.user_uuid = uuid.uuid4()
        user.set_password(password)
        user.save()
        user.profile.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return render(request, 'file/upload.html', {'user': user})
                # albums = Album.objects.filter(user=request.user)
                # return render(request, 'music/upload.html', {'albums': albums})
    else:
        return render(request, 'user/register.html', {'form': form, })


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                # albums = Album.objects.filter(user=request.user)
                return render(request, 'user/user_homepage.html', {user: 'user'})
            else:
                return render(request, 'user/login_page.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'user/login_page.html', {'error_message': 'Invalid login'})
    return render(request, 'user/login_page.html')


def password_reset_by_email(request):  # TODO: complete function - password forgot reset
    return render(request, 'check_success.html')

@login_required(login_url='/user/login/')
def logout(request):
    auth_logout(request)
    return render(request, 'user/logout.html')  # TODO: redirect logout to login-page
    # form = UserProfileForm(request.POST or None)
    # context = {
    #     "form": form,
    # }
    # return render(request, 'user/logout.html', context)


# @login_required(login_url='/user/login/')
# def password_reset_by_user(request):
#     form = PasswordResetForm(request.POST or None)
#     if form.is_valid():
#         user = request.user
#         old_password = form.cleaned_data['old_password']
#         new_pass1 = form.cleaned_data['new_password']
#         new_pass2 = form.cleaned_data['confirm_password']
#         if new_pass1 == new_pass2:
#             checkuser = authenticate(username=user.username, password=old_password)
#             if checkuser is not None:
#                 if checkuser.is_active:
#                     user.set_password(new_pass1)
#                     user.save()
#                     return render(request, 'check_success.html')
#             return render(request, 'check_success.html')
#         else:  # new password and confirmation does not match
#             return render(request, 'user/reset_by_user.html', {'form': form, 'error_message': "密码不一致"})
#     return render(request, 'user/reset_by_user.html', {'form': form, })

@login_required(login_url='/user/login/')  # TODO: fix function
def password_reset_by_user(request):
    # if request.method == 'POST':
    #     form = PasswordChangeForm(user=request.user, data=request.POST)
    #     if form.is_valid():
    #         form.save()
    #         update_session_auth_hash(request, form.user)
    #         # return redirect('http://www.baidu.com/')
    #         return redirect(reverse('user:homepage'))
    #     # else:
    #     #     # return redirect(reverse('user:password_reset_by_user'))
    # else:
    #     form = PasswordChangeForm(user=request.user)
    #
    # context = {'form': form, }
    # return render(request, 'user/reset_by_user.html', context)

    form = PasswordChangeForm(user=request.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        return redirect(reverse('user:homepage'))
    return render(request, 'user/reset_by_user.html', {'form': form})


#    ------------------------------------------------------------------------------------------------------------


#
# 用户群组
#
@ensure_csrf_cookie
@csrf_exempt
@login_required(login_url='/user/login/')
def create_group(request):
    c = {}
    correct_members = []
    wrong_input = []

    if request.method == 'POST':
        owner = request.user
        id_input = request.POST.get('members').split('\n')
        name_input = request.POST.get('name')

        if Group.objects.filter(group_name=name_input).exists():   # check if group with same name exists
            c = {'error': 'duplicate', }
            return JsonResponse(c)
        else:
            group = Group(owner=owner, group_name=name_input)
            group.save()

        for p in id_input:
            if User.objects.filter(Q(username=p) | Q(email=p)).exists():
                matched_user = User.objects.filter(Q(username=p) | Q(email=p))[0]
                member_record = GroupMember(share_group=group, shared_user=matched_user)
                member_record.save()
                correct_members.append(p)
            else:
                wrong_input.append(p)

        # if no valid group member is found, delete the generated group
        if len(correct_members) == 0:
            group.delete()

        member_record = GroupMember(share_group=group, shared_user=owner);
        member_record.save()

    c['correct_members'] = correct_members
    c['wrong_input'] = wrong_input
    return JsonResponse(c)


@login_required(login_url='/user/login/')
def group_management(request):
    user = request.user
    groups = Group.objects.filter(owner=user)

    # for group in groups:   # find the members in each group and store username in array (as string?)
    #     members = GroupMember.objects.filter(share_group=group)

    context = {
        'groups': groups,
        'user': user,
    }
    return render(request, 'user/group_management.html', context)


@login_required(login_url='/user/login/')
def shared_group_management(request):
    user = request.user
    records = GroupMember.objects.select_related('share_group').filter(shared_user=user)  # includes groups user owned, handle in html
    context = {
        'records': records,
        'user': user,
    }
    return render(request, 'user/shared_group_management.html', context)


@login_required(login_url='/user/login/')
def edit_group(request, group_id):
    user = request.user
    thegroup = Group.objects.select_related().filter(group_id=group_id)[0]
    members = GroupMember.objects.filter(share_group=thegroup)

    context = {
        'group': thegroup,
        'members': members,
        'user': user,
    }
    return render(request, 'user/edit-group.html', context)

@ensure_csrf_cookie
@csrf_exempt
@login_required(login_url='/user/login/')
def delete_member(request):
    group_id = request.POST.get('group')
    thegroup = Group.objects.select_related().filter(group_id=group_id)[0]
    user = request.user

    c = {}
    correct_members = []
    wrong_input = []
    if request.method == 'POST':
        to_delete = request.POST.getlist('to_delete[]')
        # to_delete = request.POST['to_delete']
        # print(to_delete)
        for p in to_delete:
            if User.objects.filter(username=p).exists(): # if matched_user is valid, do the deletion
                matched_user = User.objects.filter(username=p)[0]
                if matched_user == user:
                    c['message'] = '无法删除群主'
                    return JsonResponse(c)
                else:
                    GroupMember.objects.filter(share_group=thegroup, shared_user=matched_user).delete()
                    correct_members.append(p)
            else:
                wrong_input.append(p)

    c['correct_members'] = correct_members
    c['wrong_input'] = wrong_input
    return JsonResponse(c)

@ensure_csrf_cookie
@csrf_exempt
def add_member(request):
    c = {}
    correct_members = []
    wrong_input = []

    if request.method == 'POST':
        owner = request.user
        group_id = request.POST.get('group')
        group = Group.objects.select_related().filter(group_id=group_id)[0]
        id_input = request.POST.get('members').split('\n')

        for p in id_input:
            if User.objects.filter(Q(username=p) | Q(email=p)).exists():
                matched_user = User.objects.filter(Q(username=p) | Q(email=p))[0]
                member_record = GroupMember(share_group=group, shared_user=matched_user)
                member_record.save()
                correct_members.append(p)
            else:
                wrong_input.append(p)

    c['correct_members'] = correct_members
    c['wrong_input'] = wrong_input
    return JsonResponse(c)

@ensure_csrf_cookie
@csrf_exempt
def delete_group(request):
    c = {}
    if request.method == 'POST':
        if request.POST.get('group') != None:
            user = request.user
            target_group_id = request.POST.get('group')
            target_group = Group.objects.filter(group_id=target_group_id)[0]
            if target_group.owner != user:

user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8" />
    <title>版面理解服务 - 数字出版技术国家重点实验室</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
    <link href='stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css' type="text/css">
    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/bootstrap-switch.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/checkbox3.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/dataTables.bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/css/select2.min.css' %}">
    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/themes/flat-green.css' %}">


{#    <!-- CSS Libs -->#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/font-awesome.min.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/animate.min.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/bootstrap-switch.min.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/checkbox3.min.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/jquery.dataTables.min.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/dataTables.bootstrap.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/lib/css/select2.min.css">#}
{#    <!-- CSS App -->#}
{#    <link rel="stylesheet" type="text/css" href="../static/css/style.css">#}
{#    <link rel="stylesheet" type="text/css" href="../static/css/themes/flat-green.css">#}


</head>


<body class="flat-green">
    <div class="app-container">
        <div class="row content-container">
            <nav class="navbar navbar-default navbar-fixed-top navbar-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-expand-toggle">
                            <i class="fa fa-bars icon"></i>
                        </button>
                        <ol class="breadcrumb navbar-breadcrumb">
                            <li class="active"><i class="fa fa-globe"></i> 数字出版技术国家重点实验室</li>
                        </ol>
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-th icon"></i>
                        </button>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                            <i class="fa fa-times icon"></i>
                        </button>
                        <li>
                            <a href="#">首页</a>
                        </li>
                        <li>
                                <a href="#">文档整理</a>
                        </li>
                        <li class="dropdown danger">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">其他服务</a>
                            <ul class="dropdown-menu danger  animated fadeInDown">
                                <li>
                                    <ul class="list-group notifications">
                                        <a href="#">
                                            <li class="list-group-item">
                                                 <i class="fa fa-mortar-board"></i> 知识服务
                                            </li>
                                        </a>
                                        <a href="#">
                                            <li class="list-group-item">
                                                 <i class="fa fa-pencil-square-o"></i> 机器写作
                                            </li>
                                        </a>
                                        <a href="http://www.founder.com/" target="blank">
                                            <li class="list-group-item message">
                                                方正集团
                                            </li>
                                        </a>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown profile">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">我的账户<span class="caret"></span></a>
                            <ul class="dropdown-menu animated fadeInDown">
{#                                <li class="profile-img">#}
{#                                    <img src="../../static/img/profile/picjumbo.com_HNCK4153_resize.jpg" class="profile-img">#}
{#                                </li>#}
                                <li>
                                    <div class="profile-info">
{#                                        <button type="button" class="btn btn-default" href="{% url 'user:index' %}"><i class="fa fa-user"></i> Profile </button>#}
{#                                        <button type="button" class="btn btn-default" href="{% url 'user:login' %}"><i class="fa fa-sign-in"></i> Login </button>#}
{#                                        <button type="button" class="btn btn-default" href="{% url 'user:logout' %}"><i class="fa fa-sign-out"></i> Logout </button>#}


{#                                            <a href="{% url 'user:login' %}">#}
{#                                                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; 登录#}
{#                                            </a>#}
{#                                            <br>#}
                                            <a href="{% url 'user:homepage' %}">
                                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 用户信息
                                            </a>
                                            <br>
                                            <a href="{% url 'user:logout' %}">
                                                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; 注销
                                            </a>

{#                                        <h4 class="username">Emily Hart</h4>#}
{#                                        <p>emily_hart@email.com</p>#}
{#                                        <div class="btn-group margin-bottom-2x" role="group">#}
{#                                            <button type="button" class="btn btn-default"><i class="fa fa-user"></i> Profile</button>#}
{#                                            <button type="button" class="btn btn-default"><i class="fa fa-sign-out"></i> Logout</button>#}
{#                                        </div>#}
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>


           {% block side_bar %}
           {% endblock %}
{#            <div class="side-menu sidebar-inverse">#}
{#                <nav class="navbar navbar-default" role="navigation">#}
{#                    <div class="side-menu-container">#}
{#                        <div class="navbar-header">#}
{#                            <a class="navbar-brand" href="#">#}
{#                                <div class="icon fa fa-newspaper-o"></div>#}
{#                                <div class="title"> 在线标注平台 </div>#}
{#                            </a>#}
{#                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">#}
{#                                <i class="fa fa-times icon"></i>#}
{#                            </button>#}
{#                        </div>#}
{#                        <ul class="nav navbar-nav" >#}
{#                            <li >#}
{#                                <a>#}
{#                                    <span class="icon fa fa-folder-open"></span><span class="title">添加对象</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a>#}
{#                                    <span class="icon fa fa-trash"></span><span class="title">删除对象</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a>#}
{#                                    <span class="icon fa fa-cogs"></span><span class="title">类别选择</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a>#}
{#                                    <span class="icon fa fa-save"></span><span class="title">保存修改</span>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a>#}
{#                                    <span class="icon fa fa-external-link"></span><span class="title">导出结果</span>#}
{#                                </a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                    <!-- /.navbar-collapse -->#}
{#                </nav>#}
{#            </div>#}

            <!-- Main Content -->
            {% block main_body %}
            {% endblock %}

        </div>
        <footer class="app-footer">
            <div class="wrapper">
                <span class="pull-right">2.1 <a href="#"><i class="fa fa-long-arrow-up"></i></a></span> © 2015 Copyright. </a>
            </div>
        </footer>
        <div>

            <!-- Javascript Libs -->
            <script type="text/javascript" src="{% static 'lib/js/jquery.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/bootstrap.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/Chart.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/bootstrap-switch.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/jquery.matchHeight-min.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/jquery.dataTables.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/ace/ace.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/ace/mode-html.js' %}"></script>
            <script type="text/javascript" src="{% static 'lib/js/ace/theme-github.js' %}"></script>
            <!-- Javascript -->
            <script type="text/javascript" src="{% static '/js/app.js' %}"></script>
            <script type="text/javascript" src="{% static '/js/index.js' %}"></script>

        </div>
    </div>

    </body>
</html>

user/templates/check_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Check page</title>
</head>
<body>
    <h5>failed</h5>

</body>
</html>

user/templates/check_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>congrats</title>
</head>
<body>

 <h5> Upload Success</h5>

</body>
</html>

user/templates/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}