Users_FD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"

# user/
urlpatterns = [
    # user
    url(r'^$', views.file_management, name="index"),  # 主页跳转 - TBD

    url(r'^register/$', views.register, name='register'),

    url(r'^login/$', views.login, name='login'),

    url(r'^logout/$', views.logout, name='logout'),

    url(r'^password_reset_by_user$', views.password_reset_by_user, name='password_reset_by_user'),

    url(r'^password_reset_by_email', views.password_reset_by_email, name='password_reset_by_email'),

    url(r'^user_homepage/$', views.homepage, name='homepage'),


    # group
    url(r'^group_management/$', views.group_management, name='group_management'),

    url(r'^shared_group_management/$', views.shared_group_management, name='shared_group_management'),

    url(r'^create_group/$', views.create_group, name='create_group'),

    url(r'^(?P<group_id>[0-9a-f-]+)$', views.edit_group, name='edit_group'),

    url(r'^delete_member/$', views.delete_member, name='delete_member'),
    # url(r'^(?P<group_id>[0-9a-f-]+)/delete_member/$', views.delete_member, name='delete_member'),

    url(r'^add_member/$', views.add_member, name='add_member'),

    url(r'^delete_group/$', views.delete_group, name='delete_group'),



    # file
    url(r'^file_upload/$', views.file_upload, name='file_upload'),

    url(r'^file_management/$', views.file_management, name='file_management'),
    url(r'^file_management_by_modify_time/$', views.file_management_by_modify_time, name='file_management_by_modify_time'),
    url(r'^file_management_by_filename/$', views.file_management_by_filename, name='file_management_by_filename'),

    url(r'^shared_file_view/$', views.shared_file_view, name='shared_file_view'),

    url(r'^group_files_view/$', views.group_file_view, name='group_files_view'),

    url(r'^delete_file/$', views.delete_file, name='delete_file'),

    url(r'^share_file/$', views.share_file, name='share_file'),

    url(r'^share_file_to_group/$', views.share_file_to_group, name='share_file_to_group'),

    url(r'^edit_file/$', views.edit_file, name='edit_file'),

    url(r'^share_status/(?P<file_guid>[0-9a-f-]+)$', views.share_status_management, name='share_status_management'),

    url(r'^remove_share_record/$', views.remove_share_record, name='remove_share_record'),

    # url(r'^sort_file/$', views.sort_file, name='sort_file'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import uuid


# 用户信息
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    cellphone = models.CharField(max_length=20, blank=True, default='')
    user_uuid = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False, primary_key=True)

    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)


post_save.connect(create_user_profile, sender=User)


# 文件信息
class File(models.Model):
    gu_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False, primary_key=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='file_owner')

    # 正式server只存文件路径 #
    # path = models.CharField(max_length=256)
    path = models.FileField(upload_to='user_files/')

    # @property
    # def filename(self):
    #     name = self.path.name.split("/")[1].replace('_', ' ').replace('-', ' ')
    #     return name
    filename = models.CharField(max_length=255)

    total_page = models.PositiveIntegerField(default=0)
    date_uploaded = models.DateTimeField('date file uploaded', auto_now_add=True)
    last_modified = models.DateTimeField('date last modified', auto_now=True)

    def __str__(self):
        return self.filename + " ; " + self.owner.username + " ; " + self.path.url


# 分享组信息 (组长 + 组_ID)
class Group(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='group_owner')
    group_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False)
    group_name = models.CharField(max_length=255, default='', unique=True)

    def __str__(self):
        return self.owner.username + ' ；' + str(self.group_name)


# 标注信息
class Label(models.Model):
    label_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True, editable=False, primary_key=True)
    labeled_file = models.ForeignKey(File, on_delete=models.CASCADE, default=None)
    editor = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    category = models.CharField(max_length=255, default='')  # figure / table / ...
    coordinate = models.CharField(max_length=255, default='')
    status = models.CharField(max_length=255, default='')  # 识别 / 删除 / 添加


# 文件分享记录
class FileShare(models.Model):
    file_share_id = models.UUIDField(default=uuid.uuid4, null=False, auto_created=True,
                                     editable=False, primary_key=True)
    shared_file = models.ForeignKey(File, on_delete=models.CASCADE, default=None)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="shared_file_owner", default=None)
    sharer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="shared_file_sharer", default=None)
    # type = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="type", default=None)


# 群成员信息
class GroupMember(models.Model):
    share_group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None)
    shared_user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return str(self.share_group.group_name) + ' ; ' + self.shared_user.username


# 分享的群文件信息
class GroupFiles(models.Model):
    share_group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None,
                                    related_name="file_share_group")
    shared_file = models.ForeignKey(File, on_delete=models.CASCADE, default=None,
                                    related_name='shared_file')

    def __str__(self):
        return str(self.share_group.group_name) + " ; " + str(self.shared_file.filename)
    
    

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import File


class UserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(required=True)
    cellphone = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ['username', 'cellphone', 'email', 'password', ]


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['path', ]

user/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse
from .models import *

# User Authentications
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import UserProfileForm, FileUploadForm

# File Upload
from django.http import JsonResponse
from django.db.models import Q
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt


UPLOAD_FILE_TYPES = ['pdf', ]

# Create your views here.

#
# 用户系统
#
def register(request):
    form = UserProfileForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.profile.cellphone = form.cleaned_data['cellphone']
        # user.profile.user_uuid = uuid.uuid4()
        user.set_password(password)
        user.save()
        user.profile.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return render(request, 'file/upload.html', {'user': user})
                # albums = Album.objects.filter(user=request.user)
                # return render(request, 'music/upload.html', {'albums': albums})
    else:
        return render(request, 'user/register.html', {'form': form, })


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                # albums = Album.objects.filter(user=request.user)
                return render(request, 'user/user_homepage.html', {user: 'user'})
            else:
                return render(request, 'user/login_page.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'user/login_page.html', {'error_message': 'Invalid login'})
    return render(request, 'user/login_page.html')


def password_reset_by_email(request):  # TODO: complete function - password forgot reset
    return render(request, 'check_success.html')

@login_required(login_url='/user/login/')
def logout(request):
    auth_logout(request)
    return render(request, 'user/logout.html')  # TODO: redirect logout to login-page
    # form = UserProfileForm(request.POST or None)
    # context = {
    #     "form": form,
    # }
    # return render(request, 'user/logout.html', context)


# @login_required(login_url='/user/login/')
# def password_reset_by_user(request):
#     form = PasswordResetForm(request.POST or None)
#     if form.is_valid():
#         user = request.user
#         old_password = form.cleaned_data['old_password']
#         new_pass1 = form.cleaned_data['new_password']
#         new_pass2 = form.cleaned_data['confirm_password']
#         if new_pass1 == new_pass2:
#             checkuser = authenticate(username=user.username, password=old_password)
#             if checkuser is not None:
#                 if checkuser.is_active:
#                     user.set_password(new_pass1)
#                     user.save()
#                     return render(request, 'check_success.html')
#             return render(request, 'check_success.html')
#         else:  # new password and confirmation does not match
#             return render(request, 'user/reset_by_user.html', {'form': form, 'error_message': "密码不一致"})
#     return render(request, 'user/reset_by_user.html', {'form': form, })

@login_required(login_url='/user/login/')  # TODO: fix function
def password_reset_by_user(request):
    # if request.method == 'POST':
    #     form = PasswordChangeForm(user=request.user, data=request.POST)
    #     if form.is_valid():
    #         form.save()
    #         update_session_auth_hash(request, form.user)
    #         # return redirect('http://www.baidu.com/')
    #         return redirect(reverse('user:homepage'))
    #     # else:
    #     #     # return redirect(reverse('user:password_reset_by_user'))
    # else:
    #     form = PasswordChangeForm(user=request.user)
    #
    # context = {'form': form, }
    # return render(request, 'user/reset_by_user.html', context)

    form = PasswordChangeForm(user=request.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        return redirect(reverse('user:homepage'))
    return render(request, 'user/reset_by_user.html', {'form': form})


#    ------------------------------------------------------------------------------------------------------------


#
# 用户群组
#
@ensure_csrf_cookie
@csrf_exempt
@login_required(login_url='/user/login/')
def create_group(request):
    c = {}
    correct_members = []
    wrong_input = []

    if request.method == 'POST':
        owner = request.user
        id_input = request.POST.get('members').split('\n')
        name_input = request.POST.get('name')

        if Group.objects.filter(group_name=name_input).exists():   # check if group with same name exists
            c = {'error': 'duplicate', }
            return JsonResponse(c)
        else:
            group = Group(owner=owner, group_name=name_input)
            group.save()

        for p in id_input:
            if User.objects.filter(Q(username=p) | Q(email=p)).exists():
                matched_user = User.objects.filter(Q(username=p) | Q(email=p))[0]
                member_record = GroupMember(share_group=group, shared_user=matched_user)
                member_record.save()
                correct_members.append(p)
            else:
                wrong_input.append(p)

        # if no valid group member is found, delete the generated group
        if len(correct_members) == 0:
            group.delete()

        member_record = GroupMember(share_group=group, shared_user=owner);
        member_record.save()

    c['correct_members'] = correct_members
    c['wrong_input'] = wrong_input
    return JsonResponse(c)


@login_required(login_url='/user/login/')
def group_management(request):
    user = request.user
    groups = Group.objects.filter(owner=user)

    # for group in groups:   # find the members in each group and store username in array (as string?)
    #     members = GroupMember.objects.filter(share_group=group)

    context = {
        'groups': groups,
        'user': user,
    }
    return render(request, 'user/group_management.html', context)


@login_required(login_url='/user/login/')
def shared_group_management(request):
    user = request.user
    records = GroupMember.objects.select_related('share_group').filter(shared_user=user)  # includes groups user owned, handle in html
    context = {
        'records': records,
        'user': user,
    }
    return render(request, 'user/shared_group_management.html', context)


@login_required(login_url='/user/login/')
def edit_group(request, group_id):
    user = request.user
    thegroup = Group.objects.select_related().filter(group_id=group_id)[0]
    members = GroupMember.objects.filter(share_group=thegroup)

    context = {
        'group': thegroup,
        'members': members,
        'user': user,
    }
    return render(request, 'user/edit-group.html', context)

@ensure_csrf_cookie
@csrf_exempt
@login_required(login_url='/user/login/')
def delete_member(request):
    group_id = request.POST.get('group')
    thegroup = Group.objects.select_related().filter(group_id=group_id)[0]
    user = request.user

    c = {}
    correct_members = []
    wrong_input = []
    if request.method == 'POST':
        to_delete = request.POST.getlist('to_delete[]')
        # to_delete = request.POST['to_delete']
        # print(to_delete)
        for p in to_delete:
            if User.objects.filter(username=p).exists(): # if matched_user is valid, do the deletion
                matched_user = User.objects.filter(username=p)[0]
                if matched_user == user:
                    c['message'] = '无法删除群主'
                    return JsonResponse(c)
                else:
                    GroupMember.objects.filter(share_group=thegroup, shared_user=matched_user).delete()
                    correct_members.append(p)
            else:
                wrong_input.append(p)

    c['correct_members'] = correct_members
    c['wrong_input'] = wrong_input
    return JsonResponse(c)

@ensure_csrf_cookie
@csrf_exempt
def add_member(request):
    c = {}
    correct_members = []
    wrong_input = []

    if request.method == 'POST':
        owner = request.user
        group_id = request.POST.get('group')
        group = Group.objects.select_related().filter(group_id=group_id)[0]
        id_input = request.POST.get('members').split('\n')

        for p in id_input:
            if User.objects.filter(Q(username=p) | Q(email=p)).exists():
                matched_user = User.objects.filter(Q(username=p) | Q(email=p))[0]
                member_record = GroupMember(share_group=group, shared_user=matched_user)
                member_record.save()
                correct_members.append(p)
            else:
                wrong_input.append(p)

    c['correct_members'] = correct_members
    c['wrong_input'] = wrong_input
    return JsonResponse(c)

@ensure_csrf_cookie
@csrf_exempt
def delete_group(request):
    c = {}
    if request.method == 'POST':
        if request.POST.get('group') != None:
            user = request.user
            target_group_id = request.POST.get('group')
            target_group = Group.objects.filter(group_id=target_group_id)[0]
            if target_group.owner != user:

user/templates/file/file_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>file_base</title>
</head>
<body>
    {% extends 'file/../base.html' %}

    {% block side_bar %}
        <div class="side-menu sidebar-inverse">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="side-menu-container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <div class="icon fa fa-briefcase"></div>
                                <div class="title"> 文件管理 </div>
                            </a>
                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                                <i class="fa fa-times icon"></i>
                            </button>
                        </div>
                        <ul class="nav navbar-nav" >
                            <li>
                                <a href="{% url 'user:file_management' %}">
                                    <span class="icon fa fa-folder-open"></span><span class="title">我的文件</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'user:shared_file_view' %}">
                                    <span class="icon fa fa-share-alt"></span><span class="title">与我分享</span>
                                </a>
                            </li>
{#                            <li >#}
{#                                <a>#}
{#                                    <span class="icon fa fa-share-alt-square"></span><span class="title">群组文件</span>#}
{#                                </a>#}
{#                            </li>#}
                            <li>
                                <a href="{% url 'user:homepage' %}">
                                    <span class="icon fa fa-newspaper-o"></span><span class="title">用户中心</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
        </div>
    {% endblock %}

</body>
</html>

user/templates/file/group_share_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>群分享文件</title>
</head>
<body>
    <script type="text/javascript">
        var current_file_guid = '';

        function select_file(element){
            current_file_guid = element.id;
            console.log(current_file_guid);
        }
    </script>

   {% extends 'file/file_base.html' %}
   {% block main_body %}
       <div class="side-body">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                 <li role="presentation"><a href="{% url 'user:shared_file_view' %}">个人分享文件</a></li>
                 <li role="presentation" class="active"><a href="{% url 'user:group_files_view' %}">群分享文件</a ></li>
            </ul>


            {#   group files   #}
            {% if msg_code == 0 %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"> 文件名 </th>
                        <th scope="col"> 上传者 </th>
                        <th scope="col"> 分享组 </th>
                        <th scope="col"> 最后修改时间 </th>
                    </tr>
                    </thead>

                    {% for record in group_files %}
                        <tr id={{  record.shared_file.gu_id }} oncontextmenu="select_file(this)">
                            <td>{{ record.shared_file.filename }}</td>
                            <td>{{ record.shared_file.owner.username }}</td>
                            <td>{{ record.share_group.group_name }}</td>
                            <td>{{ record.shared_file.last_modified }}</td>

                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if msg_code == 1 %}
                <h5> 还没有人与您分享文件 </h5>
            {% endif %}

       </div>
    {% endblock %}

</body>
</html>

user/templates/file/shared_with_me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户分享文件</title>
</head>
<body>
    <script type="text/javascript">
        var current_file_guid = '';

        function select_file(element){
            current_file_guid = element.id;
            console.log(current_file_guid);
        }
    </script>

    {% extends 'file/file_base.html' %}
    {% block main_body %}
        <div class="side-body">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                 <li role="presentation" class="active"><a href="{% url 'user:shared_file_view' %}">个人分享文件</a></li>
                 <li role="presentation"><a href="{% url 'user:group_files_view' %}">群分享文件</a ></li>
            </ul>

            {#   user files   #}
            {% if msg == 0 %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"> 文件名 </th>
                        <th scope="col"> 上传者 </th>
{#                        <th scope="col"> UUID </th>#}
                        <th scope="col"> 最后修改时间 </th>
                    </tr>
                    </thead>

                    {% for file in shared_files %}
                        <tr id={{  file.shared_file.gu_id }} oncontextmenu="select_file(this)">
                            <td>{{ file.shared_file.filename }}</td>
                            <td>{{ file.owner.username }}</td>
{#                            <td>{{ file.shared_file.gu_id }}</td>#}
                            <td>{{ file.shared_file.last_modified }}</td>


                            {# 标注键 #}
    {#                        <td>#}
    {#                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#">#}
    {#                                标注文件#}
    {#                            </button>#}
    {#                        </td>#}

                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if msg == 1 %}
                <h5> 还没有人与您分享文件 </h5>
            {% endif %}

        </div>
    {% endblock %}

</body>
</html>

user/templates/file/upload.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title> 用户系统 </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    {% extends 'file/file_base.html' %}

{#    <script type="text/javascript">#}
        {#function FileUpload() {#}
        {#    var form_data = new FormData();#}
        {#    var file = $('#file_upload')[0].files[0];#}
        {#    form_data.append('file',file);#}
        {#    $.ajax({#}
        {#        url:'/user/upload/',#}
        {#        type:'POST',#}
        {#        data: form_data,#}
        {#        processData: false, // tell jquery not to process the data#}
        {#        contentType: false, // tell jquery not to set contentType#}
        {#        success: function (res) {#}
        {#            alert(res['message']);#}
        {#            console.log('ojbk')#}
        {#        },#}
        {#        error: function (err) {#}
        {#            alert(err['message']);#}
        {#        }#}
        {#    });#}
        {#/}#}
{##}
{#        function show() {#}
{#            var show_msg = {{ show }};#}
{#            if (show_msg == 1) {#}
{#                alert('同名文件已存在');#}
{#            }#}
{#            console.log(show_msg);#}
{#        }#}
{#    </script>#}

    {% block main_body %}
        {# 上传新文件 #}
        <div class="container-fluid">
                <div class="side-body" >
                    <ul class="nav nav-pills" style="margin-bottom: 10px;">
                         <li role="presentation"><a href="{% url 'user:file_management' %}">文件列表</a></li>
                         <li role="presentation" class="active"><a href="{% url 'user:file_upload' %}">上传文件</a ></li>
                    </ul>

                    <div class="row " style="background-color: rgb(232, 236, 230);margin: 0px;padding: 0px;">
                            <div class="row-fluid" >

                                {% if show == 1 %}
                                    <script>
                                        alert('同名文件已存在，请重新上传')
                                    </script>
                                {% endif %}
                                {% if show == 0 %}
                                    <script>
                                        alert('上传成功')
                                    </script>
                                {% endif %}
                                {% if show == 2 %}
                                    <script>
                                        alert('文件格式不正确')
                                    </script>
                                {% endif %}

                                <div class="  col-sm-2 col-md-3  col-lg-3 span3" >
                                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% include 'user/../form_template.html' %}
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success"> 确定 </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                      {#  script version  #}
{#                                    <div id="upload_file_div" class="panel-body">#}
{#                                        <form id="uplaod" enctype="multipart/form-data" method="post">#}
{#                                            <input type="file" name="file_upload" id="file_upload">#}
{#                                            <button type="submit" class="button" onclick="FileUpload()">确认上传</button>#}
{#                                        </form>#}
{#                                    </div>#}




{#                                    <label for="file"class="btn btn-info">导入文件</label>#}
{#                                    <input id="file"onchange="loadFile(this.files[0])" type="file"style="display:none">#}
{#                                    <form method="post" action=" " enctype="multipart/form-data">#}
{#                                        {% csrf_token %}#}
{#                                        <input type="file" name="upload_file" />#}
{#                                        <br>#}
{#                                        <button type="submit" value="upload" class="btn btn-info"> 确认上传 </button>#}
{#                                    </form>#}
{#                                    {{ message }}#}
{##}
                            </div>
                    <div class="container editor">

                    </div>
                </div>
        </div>
    {% endblock %}

</body>

</html>